stages:
  train:
    cmd: python train.py
    deps:
    - data
    - train.py
    params:
    - epochs
    metrics:
    - dvclive.json:
        cache: false
    - evaluation.json:
        cache: false
    plots:
    - dvclive/scalars/eval/accuracy.tsv:
        cache: false
        x: step
        y: eval/accuracy
    - dvclive/scalars/train/accuracy.tsv:
        cache: false
        x: step
        y: train/accuracy
    - dvclive/scalars/eval/loss.tsv:
        cache: false
        x: step
        y: eval/loss
    - dvclive/scalars/train/loss.tsv:
        cache: false
        x: step
        y: train/loss

