plots:
- mispredicted
- loss:
    y:
      evaluation/plots/metrics/train/loss.tsv: loss
      evaluation/plots/metrics/eval/loss.tsv: loss
- accuracy:
    y:
      evaluation/plots/metrics/train/accuracy.tsv: accuracy
      evaluation/plots/metrics/eval/accuracy.tsv: accuracy
metrics:
- evaluation/metrics.json
params:
- params.yaml
stages:
  train:
    cmd:
    - python train.py data/
    deps:
    - data/
    - train.py
    - requirements.txt
    - params.yaml
    outs:
    - model
    - evaluation:
        cache: false
  inference:
    cmd: python inference.py data/
    deps:
    - data
    - model
    - inference.py
    outs:
    - predictions
    - mispredicted
artifacts:
  hackathon:
    path: model
    type: model
    labels:
    - cv
  test-model:
    path: test-model
    type: model
