stages:
  train:
    cmd: 
    - python train.py data/
    deps:
    - data/
    - train.py
    - requirements.txt
    params:
    - params.yaml:
    metrics:
    - evaluation/metrics.json:
        cache: false
    outs:
    - model
    plots:
    - evaluation/plots/metrics/train/accuracy.tsv:
        cache: false
    - evaluation/plots/metrics/eval/accuracy.tsv:
        cache: false
    - evaluation/plots/metrics/train/loss.tsv:
        cache: false
    - evaluation/plots/metrics/eval/loss.tsv:
        cache: false
  inference:
    cmd: python inference.py data/
    deps:
    - data
    - model
    - inference.py
    outs:
    - predictions
    plots:
    - mispredicted
